version: "3.8"

services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
        - 192.168.0.6:30205:5432
        environment:
        - POSTGRES_DB=postgres_restaurant
        - POSTGRES_USER=restaurant
        - POSTGRES_PASSWORD=rSUzRBlj4Sbi8625QHilqiCmcuMax2
        volumes:
            - .:/user/bd/postgres